baseURL = "/"
title = "Xceptance Documentation Hub"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["xltdoc", "docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

# log warning if link does not exist on build (instead of default ERROR, which fails the build)
refLinksErrorLevel = "WARNING"

[frontmatter]
date = [":git", "lastmod", "date", "publishDate", ":fileModTime"]
lastmod = [":git", "lastmod", "date", "publishDate", ":fileModTime"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = false
      style = "tango"
      tabWidth = 4



 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"
release-notes = "/release-notes/:title/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 85
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en.params]
# title = "Xceptance Documentation Hub"
description = "Documentation for XLT and XTC including Manuals and How-Tos"
languageName ="English"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "https://xceptance.com"
privacy_policy = "https://www.xceptance.com/en/privacy/"
doc_license = "https://www.apache.org/licenses/LICENSE-2.0"
host = "docs.xceptance.com"

rss_sections = ["docs"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
# version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/Xceptance/xlt-documentation"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/Xceptance/XLT"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
# (if this is enabled, sidebar_search_disable needs to be true as well, Algolia does not support sidebar search)
algolia_docsearch = true

# Enable local search
# offlineSearch = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

# Set to true to enable light/dark mode switch
showLightDarkModeMenu = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
#yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
#no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discussion and help from your fellow users"
#[[params.links.user]]
#	name ="Twitter"
#	url = "https://example.org/twitter"
#	icon = "fab fa-twitter"
#        desc = "Follow us on Twitter to get the latest news!"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
#        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/Xceptance/xlt-documentation"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Blog"
	url = "https://blog.xceptance.com/"
	icon = "fa fa-newspaper"
        desc = "The Xceptance Blog"

# Main menu configuration
[[menu.main]]
    identifier = "xlt"
    name = "XLT"
    weight = 5
    url = "/xlt"
[[menu.main]]
    name = "About XLT"
    weight = 1
    url = "/xlt/about-xlt"
    parent = "xlt"
[[menu.main]]
    name = "Quick Start"
    weight = 2
    url = "/xlt/load-testing/quick-start"
    parent = "xlt"
[[menu.main]]
    name = "Base Manual"
    weight = 3
    url = "/xlt/load-testing/manual"
    parent = "xlt"
[[menu.main]]
    name = "Advanced Load Testing"
    weight = 4
    url = "/xlt/load-testing/advanced"
    parent = "xlt"
[[menu.main]]
    name = "Test Suites"
    weight = 5
    url = "/xlt/load-testing/test-suites"
    parent = "xlt"
[[menu.main]]
    name = "How-Tos"
    weight = 6
    url = "/xlt/load-testing/how-tos"
    parent = "xlt"
[[menu.main]]
    name = "Glossary"
    weight = 7
    url = "/xlt/load-testing/glossary"
    parent = "xlt"
[[menu.main]]
    identifier = "xlt-RN"
    name = "Release Notes"
    weight = 8
    url = "/xlt/release-notes"
    parent = "xlt"

    
[[menu.main]]
    identifier = "xtc"
    name = "XTC"
    weight = 10
    url = "/xtc"
[[menu.main]]
    name = "Basics"
    weight = 1
    url = "/xtc/basics"
    parent = "xtc"
[[menu.main]]
    name = "Load Testing"
    weight = 2
    url = "/xtc/loadtesting"
    parent = "xtc"
[[menu.main]]
    name = "Monitoring"
    weight = 3
    url = "/xtc/monitoring"
    parent = "xtc"
[[menu.main]]
    name = "Integrations"
    weight = 4
    url = "/xtc/integrations"
    parent = "xtc"
[[menu.main]]
    identifier = "xtc-RN"
    name = "Release Notes"
    weight = 5
    url = "/xtc/xtc-release-notes"
    parent = "xtc"
